version: "3.9"

services:
  validador:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    env_file:
      - .env

